services:
  - type: web
    name: n8n-mcp-server
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: N8N_BASE_URL
        value: https://n8n.boris-spiegl.workers.dev/api/v1
      - key: N8N_API_KEY
        value: tGhOC7BxdXn3a0LbVLOpjZe06oTJuKQ8pI4lYRz6n8c
    numInstances: 1 